### ISSUE TITLE
block-size doesn't work

### ISSUE THREAD

**Issue by kyonRay** [hot-stuff/libhotstuff#2]
Hi Ted Yin,
I run the demo with (block-size=1, enable HOTSTUFF_ENABLE_BENCHMARK), and it works well:
```shell
# run server
$ ./scripts/run_demo.sh
# run client
$ ./scripts/run_demo_client.sh > hs1.txt 2>&1
# run thr_hist.py
$ cat hs1.txt | python3 ./scripts/thr_hist.py 

# thr_hist.py output
[437, 420, 485, 458, 479, 493, 468, 469, 504, 491, 420, 439, 489, 483, 462, 
475, 456, 460, 513, 515, 231]
lat = 8.476ms
lat = 8.201ms
```

But when the block-size set to 2, it comes:
```shell
$ ./scripts/run_demo.sh

$ ./scripts/run_demo_client.sh > hs2.txt 2>&1

$ cat hs2.txt | python3 ./scripts/thr_hist.py 

# thr_hist.py output
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
lat = 11658.689ms
lat = 12006.291ms
```
It falls down dramatically, and the stranger thing is yet to come:
I set the block-size to 8000, it comes:
```shell
$ ./scripts/run_demo.sh

$ ./scripts/run_demo_client.sh > hs8000.txt 2>&1

$ cat hs8000.txt | python3 ./scripts/thr_hist.py 

# thr_hist.py output
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
lat = 11787.811ms
lat = 12012.320ms
```
I didn't figure out why is this happend.

**Comment by Determinant** [comment]
It is normal because you're not loading the system with sufficient amount of pending commands, so the system gets "starved". It could be even worse if you increase the block size without proper increase in the load, since the current code has fix block size and doesn't have fancy heuristics to generate dummy blocks to always make a commit when it is idle (see the evaluation part of the paper for more details). On the other hand, the demo scripts are mostly for the purpose of a minimal setup that runs out of the box, and the logs are human readable, while it is not aimed at being a universal script that can be used to do a fully deployed experiment. To do a more serious one, you'll need to run more clients or try to let each client simulate more command requests `--max-async` in parallel. The client program code should be short and it is always welcome to contribute some documentation since I've been busy recently...
