### ISSUE TITLE
[Question]No found newView method in pacemaker

### ISSUE THREAD

**Issue by GrapeBaBa** [hot-stuff/libhotstuff#6]
After read paper, there should be two newView related method, however not found in code. Am I missing anything?

**Comment by Determinant** [comment]
Yes, I'm afraid you should refer to the paper. There is *no* explicit view-change operation in HotStuff -- one of its major advantage (see the final pseudocode in the paper).

**Comment by Determinant** [comment]
If you are talking about `onNextSyncView` and `onReceiveNewView` methods in the pseudo-code skeleton, they're for the purpose of showing how one could craft her own PaceMaker. The methods and code in the actual implementation may vary. In short, the PaceMaker implementation, unlike the core consensus logic, is less specified in our paper, on purpose. Because it only affects performance/liveness, and very much coupled to the application you use the consensus for. The code in `liveness.h` merely serves as a naive example which is about a round-robin scheme that is typically mentioned by other works.

**Comment by GrapeBaBa** [comment]
> If you are talking about `onNextSyncView` and `onReceiveNewView` methods in the pseudo-code skeleton, they're for the purpose of showing how one could craft her own PaceMaker. The methods and code in the actual implementation may vary. In short, the PaceMaker implementation, unlike the core consensus logic, is less specified in our paper, on purpose. Because it only affects performance/liveness, and very much coupled to the application you use the consensus for. The code in `liveness.h` merely serves as a naive example which is about a round-robin scheme that is typically mentioned by other works.
> 
> I'm happy to have more discussion with you in private and see whether I can help.

Thanks, I see it.
