### ISSUE TITLE
[Question]prop.proposer in vote

### ISSUE THREAD

**Issue by GrapeBaBa** [hot-stuff/libhotstuff#7]
```
void HotStuffCore::on_receive_proposal(const Proposal &prop) {
    LOG_PROTO("got %s", std::string(prop).c_str());
    block_t bnew = prop.blk;
    sanity_check_delivered(bnew);
    update(bnew);
    bool opinion = false;
    if (bnew->height > vheight)
    {
        if (bnew->qc_ref && bnew->qc_ref->height > b_lock->height)
        {
            opinion = true; // liveness condition
            vheight = bnew->height;
        }
        else
        {   // safety condition (extend the locked branch)
            block_t b;
            for (b = bnew;
                b->height > b_lock->height;
                b = b->parents[0]);
            if (b == b_lock) /* on the same branch */
            {
                opinion = true;
                vheight = bnew->height;
            }
        }
    }
    LOG_PROTO("now state: %s", std::string(*this).c_str());
    if (bnew->qc_ref)
        on_qc_finish(bnew->qc_ref);
    on_receive_proposal_(prop);
    if (opinion && !vote_disabled)
        do_vote(prop.proposer,
            Vote(id, bnew->get_hash(),
                create_part_cert(*priv_key, bnew->get_hash()), this));
}
```

As described in paper, in the on_receive_proposal function replica could send voteMsg to a leader which decided by pacemaker getLeader function. However in this code it only pass the proposer of the proposal, am I missing anything here?

**Comment by Determinant** [comment]
That's a good catch. Yes, it should send to the leader determined by getLeader. Here it is a historical issue that I fixed the leader when first wrote it. Haven't changed since then. While it doesn't hurt safety, it should be improved. Thanks for pointing it out.

**Comment by Determinant** [comment]
While it is not really an issue in round-robin, the paper still describes a more generic case that the next leader is up to the PaceMaker, and in theory there could be such a PaceMaker instantiation that switches the proposer accurately and timely even for each block. So it's good to use `propser` rather than `last_proposer` in a demo Round-Robin PaceMaker.

**Comment by GrapeBaBa** [comment]
@Determinant Thanks. I see it.

**Comment by GrapeBaBa** [comment]
@Determinant I saw this code again, I have more thoughts. First it seems the proposer is not changed after rotating process, actually it is a fixed proposer in a long time. If one replica failed, after some time it back up again, the proposer of this replica may be different with others, it may always vote to wrong proposer however no impact consensus if other replicas all works right. 
So it seems `last_proposer` more accurate.

**Comment by Determinant** [comment]
Indeed. I might have lost my memory when we first had the discussion and decided to change it. It actually should be last_proposer -- at least it is more appropriate for this "naive" version of round-robin Pacemaker. Also notice that in https://github.com/hot-stuff/libhotstuff/commit/88f2ebc8ab988d29c892661367e200e41a0c2723 I adjusted voting to exactly reflect what's in the pseudo-code of the paper (the consensus part is now generic and only sends votes to the "next" proposer that the Pacemaker suggests). I feel it is closely related. I like the current state because the consensus part now is as generic as the paper writes, whereas using `last_proposer` seems like a better fit for the purpose of this simple Pacemaker.
